[package]
name = "image_processing"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.7"
imageproc = "0.21.0"
nalgebra = "*"
rand = "0.7.3"
